layout_spectrum: 0.7459721
color:
  saturation: 0.1404162
  lightness: 0.02678231
  brandStrength: 1
  brandColors:
    - '#010000'
    - '#015E84'
    - '#4F6F24'
    - '#81B33C'
    - '#7D0E13'
  rhythmicContrast: 0.9672801
typography_spectrum: 0.08155943
name: OnlincolnRoad
