collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3442535
  brandStrength: 1
  rhythmicContrast: 0.9672801
  brandColors:
    - '#010000'
    - '#015E84'
    - '#4F6F24'
    - '#81B33C'
    - '#7D0E13'
  lightness: 0.02678231
typography_spectrum: 0.4860365
layout_spectrum: 0.1960257
name: OnlincolnRoad
